// Fashion Images
import f1 from "../assets/BAnner4_files/Fashion/1783150937198_1b126a1a-259c-4e77-8039-503fb250daad1651661065083HERENOWMenWhiteSlimFitStripedCasualShirt1.jpg";
import f2 from "../assets/BAnner4_files/Fashion/1783150937199_36e45e27-0ae1-4255-af50-bafbe704e5791651661065092HERENOWMenWhiteSlimFitStripedCasualShirt3.jpg";
import f3 from "../assets/BAnner4_files/Fashion/1783151292475_bnbn1.jpg";
import f4 from "../assets/BAnner4_files/Fashion/1783151292475_bnbn3.jpg";
import f5 from "../assets/BAnner4_files/Fashion/1783151405015_ascscscscccswefsdvdd1.jpg";
import f6 from "../assets/BAnner4_files/Fashion/1783153348829_buynewtrend-women-maroon-cotton-blend-top-product-images-rvb22aqlk7-0-202201130044.jpg";
import f7 from "../assets/BAnner4_files/Fashion/1783153428934_deel-band-women-rayon-embroidered-kurta-pant-dupatta-set-product-images-rvz2bvyrm2-0-202404071602.webp";
import f8 from "../assets/BAnner4_files/Fashion/1784175199016_elqpri-girls-lehenga-choli-ethnic-wear-embroidered-lehenga-choli-and-dupatta-set-red-pack-of-1-9-10-years-product-images-rvck5u956f-0-202309191835.webp";

// Electronics Images
import e1 from "../assets/BAnner4_files/Electronics/1783148201496_ypjcazZmDZ-VivoY05-494793014-i-1.jpg";
import e2 from "../assets/BAnner4_files/Electronics/1783148372906_samsung-s24-ultra-5g-512-gb-12-gb-ram-titanium-gray-mobile-phone-digital-o494352159-p607431532-0-202401191135.webp";
import e3 from "../assets/BAnner4_files/Electronics/1783148590659_samsung-galaxy-a15-5g-128-gb-8-gb-ram-blue-black-mobile-phone-digital-o494351803-p607184842-0-202404101102.webp";
import e4 from "../assets/BAnner4_files/Electronics/1783148700934_apple-iphone-13-128-gb-starlight-digital-o491997700-p590798551-0-202208221207.webp";
import e5 from "../assets/BAnner4_files/Electronics/1783823737803_apple-iphone-13-128-gb-pink-digital-o491997703-p590798557-0-202208221207.webp";

// Home & Kitchen Images
import h1 from "../assets/BAnner4_files/Home and Kitchen/1783059754147_b0d92mn63m-0-1781773248923.jpg.f284fc9a37.jpg";
import h2 from "../assets/BAnner4_files/Home and Kitchen/1783060059596_01.jpg.11d09f8619.jpg";
import h3 from "../assets/BAnner4_files/Home and Kitchen/1784180059545_x1.webp";
import h4 from "../assets/BAnner4_files/Home and Kitchen/1784201597918_b0d731dwjm-1.jpeg.fb1bb062e9_(1).jpeg";

// Beauty Images
import b1 from "../assets/BAnner4_files/Beauty/1783066254118_olay-total-effect-7-in-one-day-cream-gentle-spf-15-50-gm-prod-o1051928-p608298952-0-202403020041.jpg";
import b2 from "../assets/BAnner4_files/Beauty/1783066276851_elovera-cream-150gm-prod-o327036-p608295354-0-202403012338.webp";
import b3 from "../assets/BAnner4_files/Beauty/1783153777319_nandika-beauty-massage-cream-wine-1-kg-prod-o1009518-p608316885-0-202403020848.jpg";
import b4 from "../assets/BAnner4_files/Beauty/1784176825709_mars-hd-2in1-nutration-for-skin-foundation-golden-beige-f07-product-images-orvjaeibjcv-p603656924-0-202308051112.webp";
import b5 from "../assets/BAnner4_files/Beauty/1784085670093_dr-batra-s-natural-shower-gel-enriched-with-olive-extract-pack-of-2-x-200-gm-1-s-prod-o1111474-p608303303-0-202403020330.webp";

// Bags Images
import bg1 from "../assets/BAnner4_files/BAgs/1783072675993_1731424289008_ksc-khatushyam-collection-grey-pu-for-women-handheld-bag-product-images-rvoxe6ocho-0-202405282359.webp";
import bg2 from "../assets/BAnner4_files/BAgs/1783072916189_ksc-khatushyam-collection-black-pu-for-women-handheld-bag-product-images-rvkg3apiuk-0-202405282358.webp";
import bg3 from "../assets/BAnner4_files/BAgs/1783154438181_blubags-waterproof-school-backpack-36-l-laptop-bag-college-backpack-school-bag-product-images-rvpoeah0vm-0-202312201358.webp";
import bg4 from "../assets/BAnner4_files/BAgs/1783929883577_ushawu-medium-dome-satchel-model2-460815865_brown-2-202408141116.jpg";
import bg5 from "../assets/BAnner4_files/BAgs/1784173083253_zeden-green-polyester-laptop-backpack-35-l-product-images-rvxx7hwck0-0-202406101401.jpg";

// Shoes Images
import s1 from "../assets/BAnner4_files/shoes/1783066901241_file_1734774478545_1017934b-ebb7-4394-ab4e-8033671295541721124227083ASTEROIDMenColourblockedSuedeSneakers1.jpg";
import s2 from "../assets/BAnner4_files/shoes/1783933660323_aaaaa1.jpg";
import s3 from "../assets/BAnner4_files/shoes/1784021907626_fabbmate-casual-sports-shoes-white-sneakers-for-women-girls-white-shoes-product-images-rvouh9agls-0-202406162001.webp";
import s4 from "../assets/BAnner4_files/shoes/1784176426537_birde-comfortable-regular-wear-blue-sports-shoe-for-kids-product-images-rvq8camdzw-0-202406131255.jpg";

// Sandals Images
import sd1 from "../assets/BAnner4_files/sandle/1783071021376_piclite-slipper-for-women-daily-use-flipflops-ladies-slipper-casual-doctor-ortho-slipper-pack-of-1lh5-blue-7-product-images-rvwsfbtzkt-0-202401241802.jpg";
import sd2 from "../assets/BAnner4_files/sandle/1783934481750_aqualite-women-black-casual-shoes-product-images-rvoz5uufey-0-202305241601.webp";
import sd3 from "../assets/BAnner4_files/sandle/1784174986683_aqualite-s-trendy-and-stylish-orange-flip-flops-slides-for-women-product-images-rvr9enxkgt-0-202304181628.jpg";
import sd4 from "../assets/BAnner4_files/sandle/1784178419682_paragon-k6015l-women-sandals-casual-sandals-stylish-comfortable-durable-for-daily-wear-product-images-rvvoayb8w2-0-202309061241.jpg";

// Jewellery Images
import j1 from "../assets/BAnner4_files/Jwellery/1783175807260_dangar-enterprise-kundan-white-earring-for-women-and-girls-terndy-women-pooja-and-diwali-special-attractive-earrings-set-for-party-occasion-kundan-work-studs-triangle-shape.jpg";
import j2 from "../assets/BAnner4_files/Jwellery/1783176193654_file_1734528393445_sukkhi-ethnic-gold-plated-set-of-2-pair-temple-stud-earring-combo-for-women-product-images-rvs6la4c33-0-202202250141.jpg";
import j3 from "../assets/BAnner4_files/Jwellery/1783176978866_youbella-women-gold-plated-drop-earrings-for-women-golden-ybear_31222-product-images-rvvcu7jgpl-0-202207250611.jpg";
import j4 from "../assets/BAnner4_files/Jwellery/1783344768885_giva-sterling-silver-adjustable-wine-twirling-petal-ring-product-images-rvyplqevz2-0-202210200440.webp";

export interface ReviewItem {
  id: string;
  name?: string;
  userName?: string;
  avatar?: string;
  rating: number;
  date: string;
  comment: string;
}

export interface Product {
  id: number;
  name: string;
  brand?: string;
  category: string;
  categorySlug: string;
  subCategory?: string;
  subCategorySlug?: string;
  thirdCategory?: string;
  price: number;
  oldPrice: number;
  rating: number;
  reviewsCount: number;
  countInStock: number;
  description: string;
  img: string;
  img2?: string;
  images: string[];
  sizes?: string[];
  colors?: string[];
  specs?: Record<string, string>;
  isFeatured?: boolean;
  sales?: number;
  reviews?: ReviewItem[];
}

export const initialProducts: Product[] = [
  // ── Fashion (1..8) ────────────────────────────────────────────────────────
  {
    id: 1,
    name: "Men's Striped Casual Shirt",
    brand: "HERE&NOW",
    category: "Fashion",
    categorySlug: "fashion",
    subCategory: "Men",
    subCategorySlug: "men",
    thirdCategory: "Casual Shirts",
    price: 499,
    oldPrice: 999,
    rating: 4,
    reviewsCount: 18,
    countInStock: 45,
    description: "Slim fit striped casual shirt tailored with breathable premium cotton. Ideal for workday elegance or weekend social gatherings.",
    img: f1,
    img2: f2,
    images: [f1, f2, f1, f2],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White Stripe", "Blue Stripe"],
    specs: {
      Brand: "HERE&NOW",
      Material: "100% Breathable Cotton",
      "Fit Type": "Slim Fit",
      Collar: "Spread Collar",
      Sleeve: "Full Sleeves",
      Pattern: "Striped",
      Origin: "India",
    },
    isFeatured: true,
    sales: 124,
  },
  {
    id: 2,
    name: "Men's Slim Fit Shirt",
    brand: "HERE&NOW",
    category: "Fashion",
    categorySlug: "fashion",
    subCategory: "Men",
    subCategorySlug: "men",
    thirdCategory: "Casual Shirts",
    price: 549,
    oldPrice: 1099,
    rating: 4,
    reviewsCount: 22,
    countInStock: 60,
    description: "Classic slim fit shirt with a structured silhouette and soft-washed finish for day-long effortless confidence.",
    img: f2,
    img2: f1,
    images: [f2, f1, f2],
    sizes: ["M", "L", "XL"],
    colors: ["Crisp White", "Light Grey"],
    specs: {
      Brand: "HERE&NOW",
      Material: "Pure Cotton",
      "Fit Type": "Slim Fit",
      Pattern: "Textured Solid",
    },
    isFeatured: true,
    sales: 98,
  },
  {
    id: 3,
    name: "Women's Printed Summer Top",
    brand: "BuyNewTrend",
    category: "Fashion",
    categorySlug: "fashion",
    subCategory: "Women",
    subCategorySlug: "women",
    thirdCategory: "Tops & Tunics",
    price: 399,
    oldPrice: 799,
    rating: 3.5,
    reviewsCount: 14,
    countInStock: 25,
    description: "Lightweight and flowy women's casual printed top with airy flare and soft lining.",
    img: f3,
    img2: f4,
    images: [f3, f4, f3],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Maroon Floral", "Peach Pastel"],
    specs: {
      Brand: "BuyNewTrend",
      Material: "Cotton Rayon Blend",
      "Fit Type": "Regular Fit",
      Neck: "V-Neck",
    },
    sales: 76,
  },
  {
    id: 4,
    name: "Women's Casual Everyday Top",
    brand: "BuyNewTrend",
    category: "Fashion",
    categorySlug: "fashion",
    subCategory: "Women",
    subCategorySlug: "women",
    thirdCategory: "Tops & Tunics",
    price: 349,
    oldPrice: 699,
    rating: 4,
    reviewsCount: 31,
    countInStock: 52,
    description: "Versatile casual top suitable for collegiate wear, working from home, or relaxed day strolls.",
    img: f4,
    img2: f3,
    images: [f4, f3, f4],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Classic Navy", "Rust"],
    specs: {
      Brand: "BuyNewTrend",
      Material: "Soft Cotton Blend",
      Fit: "Comfort Loose Fit",
    },
    sales: 110,
  },
  {
    id: 5,
    name: "Ethnic Embroidered Kurta Set",
    brand: "Deel Band",
    category: "Fashion",
    categorySlug: "fashion",
    subCategory: "Women",
    subCategorySlug: "women",
    thirdCategory: "Kurta Sets",
    price: 699,
    oldPrice: 1299,
    rating: 5,
    reviewsCount: 47,
    countInStock: 30,
    description: "Hand-finished ethnic kurta with exquisite yoke embroidery and matching breathable bottom.",
    img: f5,
    img2: f6,
    images: [f5, f6, f7],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Emerald Green", "Teal"],
    specs: {
      Brand: "Deel Band",
      Material: "Rayon Fabric",
      Craft: "Thread Embroidery",
      Length: "Calf Length",
    },
    isFeatured: true,
    sales: 215,
  },
  {
    id: 6,
    name: "Women's Cotton Blend Top",
    brand: "BuyNewTrend",
    category: "Fashion",
    categorySlug: "fashion",
    subCategory: "Women",
    subCategorySlug: "women",
    thirdCategory: "Tops & Tunics",
    price: 299,
    oldPrice: 599,
    rating: 4,
    reviewsCount: 19,
    countInStock: 40,
    description: "Rich maroon colored everyday top featuring breathable cotton blend weaves and clean neckline stitching.",
    img: f6,
    img2: f5,
    images: [f6, f5],
    sizes: ["M", "L", "XL"],
    colors: ["Maroon"],
    specs: {
      Brand: "BuyNewTrend",
      Material: "Cotton Blend",
      Wash: "Machine Wash Cold",
    },
    sales: 83,
  },
  {
    id: 7,
    name: "Kurta Pant Dupatta Festive Set",
    brand: "Deel Band",
    category: "Fashion",
    categorySlug: "fashion",
    subCategory: "Women",
    subCategorySlug: "women",
    thirdCategory: "Kurta Sets",
    price: 850,
    oldPrice: 1500,
    rating: 5,
    reviewsCount: 65,
    countInStock: 18,
    description: "Complete 3-piece festive ethnic ensemble including embroidered straight kurta, tapered ankle pants, and floral organza dupatta.",
    img: f7,
    img2: f8,
    images: [f7, f8, f5],
    sizes: ["M", "L", "XL"],
    colors: ["Wine Red", "Rose Gold"],
    specs: {
      Brand: "Deel Band",
      "Set Contents": "Kurta, Pants, Dupatta",
      Material: "Silk Blend & Rayon",
    },
    isFeatured: true,
    sales: 340,
  },
  {
    id: 8,
    name: "Girls Lehenga Choli Set",
    brand: "Elqpri",
    category: "Fashion",
    categorySlug: "fashion",
    subCategory: "Kids",
    subCategorySlug: "kids",
    thirdCategory: "Ethnic Wear",
    price: 750,
    oldPrice: 1400,
    rating: 4.5,
    reviewsCount: 28,
    countInStock: 22,
    description: "Bright festive ethnic embroidered lehenga choli with lightweight net dupatta, tailored for supreme comfort.",
    img: f8,
    img2: f7,
    images: [f8, f7],
    sizes: ["5-6 Y", "7-8 Y", "9-10 Y", "11-12 Y"],
    colors: ["Festive Red", "Golden Yellow"],
    specs: {
      Brand: "Elqpri",
      Material: "Satin Silk Blend",
      Occasion: "Festive & Wedding",
    },
    sales: 92,
  },

  // ── Electronics (9..13) ───────────────────────────────────────────────────
  {
    id: 9,
    name: "Vivo Y05 Smartphone (64GB)",
    brand: "Vivo",
    category: "Electronics",
    categorySlug: "electronics",
    subCategory: "Smartphones",
    subCategorySlug: "smartphones",
    thirdCategory: "Budget Phones",
    price: 8999,
    oldPrice: 12999,
    rating: 4,
    reviewsCount: 54,
    countInStock: 35,
    description: "Value-packed 6.51-inch HD+ display with high-capacity 5000mAh battery and AI-powered dual camera setup.",
    img: e1,
    img2: e2,
    images: [e1, e2, e3],
    sizes: ["64GB", "128GB"],
    colors: ["Wave Green", "Mystic Blue"],
    specs: {
      Brand: "Vivo",
      RAM: "4GB RAM",
      Storage: "64GB Internal (Expandable)",
      Display: "6.51 inch Halo FullView",
      Battery: "5000 mAh",
      Warranty: "1 Year Manufacturer",
    },
    sales: 420,
  },
  {
    id: 10,
    name: "Samsung Galaxy S24 Ultra 5G (512GB)",
    brand: "Samsung",
    category: "Electronics",
    categorySlug: "electronics",
    subCategory: "Smartphones",
    subCategorySlug: "smartphones",
    thirdCategory: "Flagship Phones",
    price: 89999,
    oldPrice: 109999,
    rating: 5,
    reviewsCount: 184,
    countInStock: 15,
    description: "Titanium armor frame, embedded S-Pen, Galaxy AI camera tools, and 200MP Quad Telephoto optical zoom.",
    img: e2,
    img2: e1,
    images: [e2, e1, e3],
    sizes: ["256GB", "512GB", "1TB"],
    colors: ["Titanium Gray", "Titanium Black", "Titanium Violet"],
    specs: {
      Brand: "Samsung",
      Processor: "Snapdragon 8 Gen 3 for Galaxy",
      Display: "6.8 inch QHD+ Dynamic AMOLED 2X 120Hz",
      Camera: "200MP + 50MP + 12MP + 10MP",
      Battery: "5000 mAh Fast Wireless Charging",
    },
    isFeatured: true,
    sales: 310,
  },
  {
    id: 11,
    name: "Samsung Galaxy A15 5G (128GB)",
    brand: "Samsung",
    category: "Electronics",
    categorySlug: "electronics",
    subCategory: "Smartphones",
    subCategorySlug: "smartphones",
    thirdCategory: "5G Mobiles",
    price: 14999,
    oldPrice: 19999,
    rating: 4.2,
    reviewsCount: 78,
    countInStock: 40,
    description: "Fluid 90Hz Super AMOLED screen, 50MP triple primary camera array, and reliable Samsung Knox vault security.",
    img: e3,
    img2: e4,
    images: [e3, e4, e2],
    sizes: ["128GB", "256GB"],
    colors: ["Blue Black", "Light Blue"],
    specs: {
      Brand: "Samsung",
      RAM: "8GB",
      Display: "6.5 inch FHD+ Super AMOLED",
      Battery: "5000 mAh 25W Charging",
    },
    sales: 245,
  },
  {
    id: 12,
    name: "Apple iPhone 13 (128GB, Starlight)",
    brand: "Apple",
    category: "Electronics",
    categorySlug: "electronics",
    subCategory: "Smartphones",
    subCategorySlug: "smartphones",
    thirdCategory: "Flagship Phones",
    price: 59999,
    oldPrice: 79999,
    rating: 5,
    reviewsCount: 290,
    countInStock: 20,
    description: "Super Retina XDR OLED display, lightning-quick A15 Bionic neural chip, and Cinematic Mode 4K recording.",
    img: e4,
    img2: e5,
    images: [e4, e5],
    sizes: ["128GB", "256GB", "512GB"],
    colors: ["Starlight", "Midnight", "Blue"],
    specs: {
      Brand: "Apple",
      Chip: "A15 Bionic chip with 4-core GPU",
      Display: "6.1 inch Super Retina XDR OLED",
      WaterResistance: "IP68 rated",
    },
    isFeatured: true,
    sales: 580,
  },
  {
    id: 13,
    name: "Apple iPhone 13 (128GB, Pink)",
    brand: "Apple",
    category: "Electronics",
    categorySlug: "electronics",
    subCategory: "Smartphones",
    subCategorySlug: "smartphones",
    thirdCategory: "Flagship Phones",
    price: 59999,
    oldPrice: 79999,
    rating: 5,
    reviewsCount: 142,
    countInStock: 12,
    description: "Subtle pastel pink aluminum enclosure with Ceramic Shield front and all-day battery efficiency.",
    img: e5,
    img2: e4,
    images: [e5, e4],
    sizes: ["128GB", "256GB"],
    colors: ["Pink"],
    specs: {
      Brand: "Apple",
      Chip: "A15 Bionic chip",
      Camera: "Dual 12MP Camera system with Sensor-shift OIS",
    },
    sales: 390,
  },

  // ── Home & Kitchen (14..17) ───────────────────────────────────────────────
  {
    id: 14,
    name: "Kitchen Storage Jars Set (6 Pcs)",
    brand: "HomeNest",
    category: "Home & Kitchen",
    categorySlug: "home-kitchen",
    subCategory: "Storage & Containers",
    subCategorySlug: "storage",
    thirdCategory: "Kitchen Jars",
    price: 349,
    oldPrice: 699,
    rating: 4.3,
    reviewsCount: 42,
    countInStock: 65,
    description: "BPA-free airtight modular kitchen canisters with transparent visibility and silicone snap seals.",
    img: h1,
    img2: h2,
    images: [h1, h2, h3],
    sizes: ["Pack of 6", "Pack of 12"],
    colors: ["Clear / Black Lid"],
    specs: {
      Brand: "HomeNest",
      Material: "Food Grade BPA-Free PET",
      Capacity: "1000ml Each",
      Airtight: "Yes",
    },
    sales: 180,
  },
  {
    id: 15,
    name: "Artisan Ceramic Decorative Vase",
    brand: "Decora",
    category: "Home & Kitchen",
    categorySlug: "home-kitchen",
    subCategory: "Home Decor",
    subCategorySlug: "decor",
    thirdCategory: "Vases",
    price: 499,
    oldPrice: 899,
    rating: 3.8,
    reviewsCount: 19,
    countInStock: 28,
    description: "Nordic textured ceramic vase designed for dried pampas, botanical stalks, or modern shelf decor.",
    img: h2,
    img2: h1,
    images: [h2, h1],
    sizes: ["Standard 22cm", "Tall 30cm"],
    colors: ["Matte Off-White", "Terracotta"],
    specs: {
      Brand: "Decora",
      Material: "Kiln-Fired Ceramic",
      Finish: "Hand-textured Matte",
    },
    sales: 75,
  },
  {
    id: 16,
    name: "Multi-Tier Kitchen Countertop Organizer",
    brand: "HomeNest",
    category: "Home & Kitchen",
    categorySlug: "home-kitchen",
    subCategory: "Storage & Containers",
    subCategorySlug: "storage",
    thirdCategory: "Racks",
    price: 299,
    oldPrice: 599,
    rating: 4.1,
    reviewsCount: 33,
    countInStock: 50,
    description: "Rust-resistant coated steel wire organizer rack for spices, condiments, and mug essentials.",
    img: h3,
    img2: h4,
    images: [h3, h4],
    sizes: ["2-Tier", "3-Tier"],
    colors: ["Matte Black", "White"],
    specs: {
      Brand: "HomeNest",
      Material: "Heavy Duty Carbon Steel",
      Coating: "Anti-Rust Powder Coat",
    },
    sales: 135,
  },
  {
    id: 17,
    name: "Non-Stick Ceramic Saucepan & Pot",
    brand: "MasterChef",
    category: "Home & Kitchen",
    categorySlug: "home-kitchen",
    subCategory: "Cookware",
    subCategorySlug: "cookware",
    thirdCategory: "Pans",
    price: 399,
    oldPrice: 799,
    rating: 4.4,
    reviewsCount: 51,
    countInStock: 34,
    description: "Eco-friendly non-stick ceramic cookware with induction bottom plate and stay-cool wooden handle.",
    img: h4,
    img2: h3,
    images: [h4, h3],
    sizes: ["20cm", "24cm"],
    colors: ["Cream Almond", "Slate Grey"],
    specs: {
      Brand: "MasterChef",
      Base: "Induction & Gas Compatible",
      Coating: "Ceramic Non-Stick 100% PFOA Free",
    },
    isFeatured: true,
    sales: 190,
  },

  // ── Beauty (18..22) ───────────────────────────────────────────────────────
  {
    id: 18,
    name: "Olay Total Effects 7-in-1 Day Cream",
    brand: "Olay",
    category: "Beauty",
    categorySlug: "beauty",
    subCategory: "Skincare",
    subCategorySlug: "skincare",
    thirdCategory: "Face Creams",
    price: 399,
    oldPrice: 699,
    rating: 4.6,
    reviewsCount: 89,
    countInStock: 60,
    description: "Daily age-defying moisturizer with SPF 15, Vitamin B3, Pro-Vitamin B5, and Vitamin E to fight 7 signs of aging.",
    img: b1,
    img2: b2,
    images: [b1, b2, b3],
    sizes: ["50g", "100g"],
    specs: {
      Brand: "Olay",
      "Skin Type": "All Skin Types",
      SunProtection: "SPF 15",
      Formulation: "Lightweight Non-Greasy Cream",
    },
    isFeatured: true,
    sales: 410,
  },
  {
    id: 19,
    name: "Elovera Deep Moisturizing Cream",
    brand: "Glenmark",
    category: "Beauty",
    categorySlug: "beauty",
    subCategory: "Skincare",
    subCategorySlug: "skincare",
    thirdCategory: "Moisturizers",
    price: 199,
    oldPrice: 399,
    rating: 4.4,
    reviewsCount: 38,
    countInStock: 80,
    description: "Dermatologist recommended hydration cream enriched with pure Aloe Vera extracts and natural Vitamin E.",
    img: b2,
    img2: b1,
    images: [b2, b1],
    sizes: ["150g"],
    specs: {
      Brand: "Glenmark",
      "Active Ingredients": "Aloe Vera + Vitamin E",
      IdealFor: "Dry & Sensitive Skin",
    },
    sales: 165,
  },
  {
    id: 20,
    name: "Nandika Wine Nourishing Massage Cream",
    brand: "Nandika",
    category: "Beauty",
    categorySlug: "beauty",
    subCategory: "Bath & Body",
    subCategorySlug: "bath-body",
    thirdCategory: "Massage Creams",
    price: 299,
    oldPrice: 599,
    rating: 3.7,
    reviewsCount: 16,
    countInStock: 45,
    description: "Antioxidant grape polyphenols infused skin renewal massage formula for parlor-like glow.",
    img: b3,
    img2: b4,
    images: [b3, b4],
    sizes: ["500g", "1000g"],
    specs: {
      Brand: "Nandika",
      Benefits: "Skin Tightening & Radiant Glow",
      Fragrance: "Mild Red Wine Essence",
    },
    sales: 68,
  },
  {
    id: 21,
    name: "Mars HD 2-in-1 Natural Foundation",
    brand: "Mars",
    category: "Beauty",
    categorySlug: "beauty",
    subCategory: "Makeup",
    subCategorySlug: "makeup",
    thirdCategory: "Foundations",
    price: 249,
    oldPrice: 499,
    rating: 4.3,
    reviewsCount: 72,
    countInStock: 55,
    description: "Full-coverage, weightless breathable foundation with buildable matte finish and sweat-proof wear.",
    img: b4,
    img2: b3,
    images: [b4, b3],
    sizes: ["30ml"],
    colors: ["Golden Beige", "Natural Ivory", "Warm Honey"],
    specs: {
      Brand: "Mars Cosmetics",
      Coverage: "Medium to High Buildable",
      Finish: "Velvet Satin",
    },
    sales: 230,
  },
  {
    id: 22,
    name: "Dr. Batra's Olive Enriched Shower Gel",
    brand: "Dr. Batra's",
    category: "Beauty",
    categorySlug: "beauty",
    subCategory: "Bath & Body",
    subCategorySlug: "bath-body",
    thirdCategory: "Shower Gels",
    price: 349,
    oldPrice: 649,
    rating: 4.8,
    reviewsCount: 44,
    countInStock: 40,
    description: "Gentle soap-free cleansing body wash loaded with Mediterranean olive fruit oil to lock in skin moisture.",
    img: b5,
    img2: b1,
    images: [b5, b1],
    sizes: ["Pack of 2 x 200ml"],
    specs: {
      Brand: "Dr. Batra's",
      ParabenFree: "100% Yes",
      SkinNourishment: "Deep Olive Infusion",
    },
    isFeatured: true,
    sales: 195,
  },

  // ── Bags (23..27) ─────────────────────────────────────────────────────────
  {
    id: 23,
    name: "Grey PU Structured Handheld Bag",
    brand: "Khatushyam",
    category: "Bags",
    categorySlug: "bags",
    subCategory: "Handbags",
    subCategorySlug: "handbags",
    thirdCategory: "PU Handbags",
    price: 599,
    oldPrice: 1099,
    rating: 4.1,
    reviewsCount: 39,
    countInStock: 30,
    description: "Clean architectural handbag with golden metallic hardware, twin grab handles, and removable shoulder strap.",
    img: bg1,
    img2: bg2,
    images: [bg1, bg2, bg4],
    colors: ["Slate Grey", "Onyx Black"],
    specs: {
      Brand: "Khatushyam Collection",
      Material: "Premium Vegan PU Leather",
      Compartments: "2 Main + 1 Center Zipper",
    },
    isFeatured: true,
    sales: 140,
  },
  {
    id: 24,
    name: "Black Classic Structured Handbag",
    brand: "Khatushyam",
    category: "Bags",
    categorySlug: "bags",
    subCategory: "Handbags",
    subCategorySlug: "handbags",
    thirdCategory: "PU Handbags",
    price: 649,
    oldPrice: 1199,
    rating: 4.4,
    reviewsCount: 57,
    countInStock: 25,
    description: "Timeless black handbag crafted with textured scratch-resistant vegan leather and roomy organizer pockets.",
    img: bg2,
    img2: bg1,
    images: [bg2, bg1],
    colors: ["Jet Black"],
    specs: {
      Brand: "Khatushyam Collection",
      Material: "Vegan PU Leather",
      Closure: "Sturdy Metal Zip",
    },
    sales: 210,
  },
  {
    id: 25,
    name: "BluBags 36L Waterproof Backpack",
    brand: "BluBags",
    category: "Bags",
    categorySlug: "bags",
    subCategory: "Backpacks",
    subCategorySlug: "backpacks",
    thirdCategory: "School Bags",
    price: 799,
    oldPrice: 1499,
    rating: 4.7,
    reviewsCount: 112,
    countInStock: 48,
    description: "Ergonomic multi-compartment travel & college backpack with rain shield coating and cushioned shoulder straps.",
    img: bg3,
    img2: bg4,
    images: [bg3, bg4, bg5],
    colors: ["Navy Blue", "Charcoal"],
    specs: {
      Brand: "BluBags",
      Capacity: "36 Litres",
      LaptopSleeve: "Fits up to 15.6 inch",
      WaterResistant: "Yes",
    },
    isFeatured: true,
    sales: 520,
  },
  {
    id: 26,
    name: "Ushawu Medium Dome Satchel",
    brand: "Ushawu",
    category: "Bags",
    categorySlug: "bags",
    subCategory: "Satchels",
    subCategorySlug: "satchels",
    thirdCategory: "Dome Satchels",
    price: 899,
    oldPrice: 1699,
    rating: 4.2,
    reviewsCount: 26,
    countInStock: 16,
    description: "Chic curved dome silhouette finished in warm saddle brown with dual contrast stitch details.",
    img: bg4,
    img2: bg3,
    images: [bg4, bg3],
    colors: ["Saddle Brown", "Tan"],
    specs: {
      Brand: "Ushawu",
      Material: "Faux Leather",
      Strap: "Adjustable Crossbody Strap",
    },
    sales: 88,
  },
  {
    id: 27,
    name: "Zeden 35L Green Tech Laptop Backpack",
    brand: "Zeden",
    category: "Bags",
    categorySlug: "bags",
    subCategory: "Backpacks",
    subCategorySlug: "backpacks",
    thirdCategory: "Laptop Backpacks",
    price: 999,
    oldPrice: 1899,
    rating: 4.5,
    reviewsCount: 68,
    countInStock: 32,
    description: "Durable military green polyester tech pack with dedicated fleece-lined laptop sleeve and quick-access passport pouch.",
    img: bg5,
    img2: bg1,
    images: [bg5, bg1],
    colors: ["Olive Green"],
    specs: {
      Brand: "Zeden",
      Capacity: "35 Litres",
      Fabric: "High-Density 900D Polyester",
    },
    sales: 195,
  },

  // ── Shoes (28..31) ────────────────────────────────────────────────────────
  {
    id: 28,
    name: "Asteroid Colourblocked Suede Sneakers",
    brand: "Asteroid",
    category: "Shoes",
    categorySlug: "shoes",
    subCategory: "Sneakers",
    subCategorySlug: "sneakers",
    thirdCategory: "Suede Sneakers",
    price: 999,
    oldPrice: 1999,
    rating: 4.3,
    reviewsCount: 48,
    countInStock: 35,
    description: "Retro street sneakers combining genuine suede trim, contrast colorblocking, and vulcanized rubber traction soles.",
    img: s1,
    img2: s2,
    images: [s1, s2, s3],
    sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"],
    colors: ["White / Blue / Mustard"],
    specs: {
      Brand: "Asteroid Footwear",
      Upper: "Breathable Mesh + Suede",
      Sole: "Vulcanized Grip Rubber",
    },
    isFeatured: true,
    sales: 280,
  },
  {
    id: 29,
    name: "Men's Urban Everyday Casual Shoes",
    brand: "Asteroid",
    category: "Shoes",
    categorySlug: "shoes",
    subCategory: "Casual Shoes",
    subCategorySlug: "casual-shoes",
    thirdCategory: "Casual Sneakers",
    price: 699,
    oldPrice: 1299,
    rating: 4.0,
    reviewsCount: 31,
    countInStock: 50,
    description: "Featherlight slip-on casual lace-ups with memory foam sockliner for long standing comfort.",
    img: s2,
    img2: s1,
    images: [s2, s1],
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10"],
    colors: ["Navy", "Charcoal"],
    specs: {
      Brand: "Asteroid",
      Sole: "EVA Cushioned",
      Weight: "350g per pair",
    },
    sales: 155,
  },
  {
    id: 30,
    name: "Fabbmate Women's White Platform Sneakers",
    brand: "Fabbmate",
    category: "Shoes",
    categorySlug: "shoes",
    subCategory: "Sneakers",
    subCategorySlug: "sneakers",
    thirdCategory: "White Sneakers",
    price: 599,
    oldPrice: 1099,
    rating: 4.8,
    reviewsCount: 82,
    countInStock: 42,
    description: "Trendy chunky white sneakers for women with padded collars and dirt-resistant easy-clean faux leather exterior.",
    img: s3,
    img2: s4,
    images: [s3, s4, s1],
    sizes: ["UK 4", "UK 5", "UK 6", "UK 7", "UK 8"],
    colors: ["All White"],
    specs: {
      Brand: "Fabbmate",
      PlatformHeight: "1.5 inches",
      Upper: "Easy-wipe Synthetic Leather",
    },
    isFeatured: true,
    sales: 380,
  },
  {
    id: 31,
    name: "Birde Kids Breathable Sports Running Shoes",
    brand: "Birde",
    category: "Shoes",
    categorySlug: "shoes",
    subCategory: "Sports Shoes",
    subCategorySlug: "sports-shoes",
    thirdCategory: "Kids Sports Shoes",
    price: 499,
    oldPrice: 899,
    rating: 4.2,
    reviewsCount: 29,
    countInStock: 30,
    description: "Shock-absorbing blue sports sneakers with flexible flex grooves and hook-and-loop velcro closure for kids.",
    img: s4,
    img2: s3,
    images: [s4, s3],
    sizes: ["UK 1", "UK 2", "UK 3", "UK 4", "UK 5"],
    colors: ["Cobalt Blue"],
    specs: {
      Brand: "Birde",
      Closure: "Velcro Strap + Bungee Laces",
      ToeProtection: "Reinforced Rubber Cap",
    },
    sales: 115,
  },

  // ── Sandals (32..35) ──────────────────────────────────────────────────────
  {
    id: 32,
    name: "Piclite Ortho Comfort Daily Flip Flops",
    brand: "Piclite",
    category: "Sandals",
    categorySlug: "sandals",
    subCategory: "Flip Flops",
    subCategorySlug: "flip-flops",
    thirdCategory: "Ortho Slippers",
    price: 199,
    oldPrice: 399,
    rating: 3.9,
    reviewsCount: 46,
    countInStock: 75,
    description: "Ergonomic doctor-designed orthopedic footbed flip flops for soothing heel and arch support.",
    img: sd1,
    img2: sd2,
    images: [sd1, sd2],
    sizes: ["UK 5", "UK 6", "UK 7", "UK 8"],
    colors: ["Royal Blue"],
    specs: {
      Brand: "Piclite",
      Sole: "Acupressure Micro-Cellular Rubber",
      AntiSlip: "Yes",
    },
    sales: 260,
  },
  {
    id: 33,
    name: "Aqualite Black Casual Strappy Sandals",
    brand: "Aqualite",
    category: "Sandals",
    categorySlug: "sandals",
    subCategory: "Casual Sandals",
    subCategorySlug: "casual-sandals",
    thirdCategory: "Women Flat Sandals",
    price: 249,
    oldPrice: 499,
    rating: 4.1,
    reviewsCount: 37,
    countInStock: 60,
    description: "Modern minimalist slip-on flats with soft crossover straps and durable wear-resistant base.",
    img: sd2,
    img2: sd1,
    images: [sd2, sd1],
    sizes: ["UK 5", "UK 6", "UK 7", "UK 8"],
    colors: ["Black"],
    specs: {
      Brand: "Aqualite",
      Sole: "TPR Non-Marking",
      Weight: "Lightweight 220g",
    },
    sales: 175,
  },
  {
    id: 34,
    name: "Aqualite Vibrant Orange Comfort Slides",
    brand: "Aqualite",
    category: "Sandals",
    categorySlug: "sandals",
    subCategory: "Flip Flops",
    subCategorySlug: "flip-flops",
    thirdCategory: "Slides",
    price: 179,
    oldPrice: 349,
    rating: 4.4,
    reviewsCount: 52,
    countInStock: 80,
    description: "Fun citrus-colored waterproof slides ideal for poolside relaxation, beach visits, and quick errands.",
    img: sd3,
    img2: sd4,
    images: [sd3, sd4],
    sizes: ["UK 5", "UK 6", "UK 7", "UK 8"],
    colors: ["Tangerine Orange"],
    specs: {
      Brand: "Aqualite",
      Material: "Quick-Dry EVA Molded",
      Waterproof: "100%",
    },
    sales: 310,
  },
  {
    id: 35,
    name: "Paragon K6015L Casual Comfort Sandals",
    brand: "Paragon",
    category: "Sandals",
    categorySlug: "sandals",
    subCategory: "Casual Sandals",
    subCategorySlug: "casual-sandals",
    thirdCategory: "Women Flat Sandals",
    price: 299,
    oldPrice: 599,
    rating: 4.7,
    reviewsCount: 94,
    countInStock: 45,
    description: "Renowned Paragon durability combined with gentle footbeds and adjustable ankle wrap buckle.",
    img: sd4,
    img2: sd3,
    images: [sd4, sd3],
    sizes: ["UK 5", "UK 6", "UK 7", "UK 8"],
    colors: ["Beige Tan"],
    specs: {
      Brand: "Paragon",
      Model: "K6015L",
      Durability: "High Resistance Polyurethane",
    },
    isFeatured: true,
    sales: 450,
  },

  // ── Jewellery (36..39) ────────────────────────────────────────────────────
  {
    id: 36,
    name: "Kundan White Temple Earrings Set",
    brand: "Dangar",
    category: "Jewellery",
    categorySlug: "jewellery",
    subCategory: "Earrings",
    subCategorySlug: "earrings",
    thirdCategory: "Kundan Earrings",
    price: 199,
    oldPrice: 399,
    rating: 4.3,
    reviewsCount: 36,
    countInStock: 50,
    description: "Festive triangle shaped Kundan stud earrings with faux seed pearl drops for festive and pooja occasions.",
    img: j1,
    img2: j2,
    images: [j1, j2, j3],
    colors: ["Kundan White & Gold"],
    specs: {
      Brand: "Dangar Enterprise",
      BaseMetal: "Brass Alloy",
      Plating: "22K Micron Gold Plated",
      Stone: "Faceted Kundan Glass Stones",
    },
    sales: 185,
  },
  {
    id: 37,
    name: "Sukkhi 2-Pair Gold Plated Temple Studs",
    brand: "Sukkhi",
    category: "Jewellery",
    categorySlug: "jewellery",
    subCategory: "Earrings",
    subCategorySlug: "earrings",
    thirdCategory: "Stud Earrings",
    price: 299,
    oldPrice: 599,
    rating: 4.8,
    reviewsCount: 71,
    countInStock: 40,
    description: "Set of 2 pairs of regal heritage floral temple stud earrings with durable push-back posts.",
    img: j2,
    img2: j1,
    images: [j2, j1],
    colors: ["Traditional Gold"],
    specs: {
      Brand: "Sukkhi",
      Plating: "Gold Plated",
      Units: "2 Pairs (4 Pieces)",
      Hypoallergenic: "Yes, Nickel-free",
    },
    isFeatured: true,
    sales: 290,
  },
  {
    id: 38,
    name: "YouBella Gold Plated Hanging Drop Earrings",
    brand: "YouBella",
    category: "Jewellery",
    categorySlug: "jewellery",
    subCategory: "Earrings",
    subCategorySlug: "earrings",
    thirdCategory: "Drop Earrings",
    price: 249,
    oldPrice: 499,
    rating: 4.1,
    reviewsCount: 42,
    countInStock: 55,
    description: "Modern chandelier drop earrings that shimmer with every movement, perfect for party wear.",
    img: j3,
    img2: j4,
    images: [j3, j4],
    colors: ["Yellow Gold"],
    specs: {
      Brand: "YouBella",
      Style: "Danglers & Drops",
      Weight: "Lightweight 18g",
    },
    sales: 160,
  },
  {
    id: 39,
    name: "Giva Sterling Silver Twirling Petal Ring",
    brand: "GIVA",
    category: "Jewellery",
    categorySlug: "jewellery",
    subCategory: "Rings",
    subCategorySlug: "rings",
    thirdCategory: "Silver Rings",
    price: 349,
    oldPrice: 699,
    rating: 4.9,
    reviewsCount: 118,
    countInStock: 25,
    description: "Authentic 925 hallmarked sterling silver adjustable open ring featuring rotating wine-crystal petals.",
    img: j4,
    img2: j3,
    images: [j4, j3, j1],
    colors: ["925 Silver / Wine Crystal"],
    specs: {
      Brand: "GIVA",
      Metal: "925 Sterling Silver Hallmarked",
      Size: "Free Size / Adjustable",
      Certificate: "GIVA Authenticity Card Included",
    },
    isFeatured: true,
    sales: 620,
  },
];

// Helper: load stored products from localStorage if any, or fallback
export function getStoredProducts(): Product[] {
  try {
    const raw = localStorage.getItem("app_products");
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) {
        // merge with local image references if any match id
        return parsed.map((item: any) => {
          const match = initialProducts.find((p) => p.id === item.id);
          return {
            ...item,
            img: item.img || match?.img,
            img2: item.img2 || match?.img2 || match?.img,
            images: item.images?.length ? item.images : match?.images || [item.img],
          };
        });
      }
    }
  } catch (e) {
    console.error("Error reading stored products", e);
  }
  return initialProducts;
}

export function saveStoredProducts(list: Product[]) {
  try {
    localStorage.setItem("app_products", JSON.stringify(list));
  } catch (e) {
    console.error("Error saving products", e);
  }
}

export const products: Product[] = getStoredProducts();

export function getProductById(id: string | number): Product | undefined {
  const numId = Number(id);
  const all = getStoredProducts();
  return all.find((p) => p.id === numId);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  const all = getStoredProducts();
  const normalized = categorySlug.toLowerCase().trim();
  return all.filter(
    (p) =>
      p.categorySlug.toLowerCase() === normalized ||
      p.category.toLowerCase().replace(/\s+/g, "-") === normalized ||
      p.subCategorySlug?.toLowerCase() === normalized
  );
}
