export interface Product {
  id: number;
  img: string;
  img2?: string;
  brand?: string;
  name: string;
  description?: string;
  price: number;
  oldPrice: number;
  rating: number;
}


export const products: Product[] = [
  {
    id: 1,
    img: "https://picsum.photos/seed/prod1/400/400",
    img2: "https://picsum.photos/seed/prod1b/400/400",
    name: "Wireless Headphones",
    description: "Over-ear Bluetooth headphones with noise cancellation",
    price: 1499,
    oldPrice: 2999,
    rating: 4,
  },
  {
    id: 2,
    img: "https://picsum.photos/seed/prod2/400/400",
    img2: "https://picsum.photos/seed/prod2b/400/400",
    name: "Running Shoes",
    description: "Lightweight breathable sports shoes",
    price: 899,
    oldPrice: 1799,
    rating: 5,
  },
  {
    id: 3,
    img: "https://picsum.photos/seed/prod3/400/400",
    img2: "https://picsum.photos/seed/prod3b/400/400",
    name: "Leather Handbag",
    description: "Premium faux-leather handbag with adjustable strap",
    price: 1299,
    oldPrice: 2599,
    rating: 4,
  },
  {
    id: 4,
    img: "https://picsum.photos/seed/prod4/400/400",
    img2: "https://picsum.photos/seed/prod4b/400/400",
    name: "Smart Watch",
    description: "Fitness tracking smartwatch with heart-rate monitor",
    price: 1999,
    oldPrice: 3999,
    rating: 3,
  },
  {
    id: 5,
    img: "https://picsum.photos/seed/prod5/400/400",
    img2: "https://picsum.photos/seed/prod5b/400/400",
    name: "Sunglasses",
    description: "UV-protection polarized sunglasses",
    price: 499,
    oldPrice: 999,
    rating: 4,
  },
  {
    id: 6,
    img: "https://picsum.photos/seed/prod6/400/400",
    img2: "https://picsum.photos/seed/prod6b/400/400",
    name: "Ceramic Cookware Set",
    description: "5-piece non-stick ceramic cookware set",
    price: 2499,
    oldPrice: 4999,
    rating: 5,
  },
  {
    id: 7,
    img: "https://picsum.photos/seed/prod7/400/400",
    img2: "https://picsum.photos/seed/prod7b/400/400",
    name: "Gold Plated Necklace",
    description: "Elegant gold plated necklace with pendant",
    price: 799,
    oldPrice: 1599,
    rating: 4,
  },
  {
    id: 8,
    img: "https://picsum.photos/seed/prod8/400/400",
    img2: "https://picsum.photos/seed/prod8b/400/400",
    name: "Sandals",
    description: "Comfortable everyday flat sandals",
    price: 399,
    oldPrice: 799,
    rating: 3,
  },
  {
    id: 9,
    img: "https://picsum.photos/seed/prod8/400/400",
    img2: "https://picsum.photos/seed/prod8b/400/400",
    name: "Sandals",
    description: "Comfortable everyday flat sandals",
    price: 399,
    oldPrice: 799,
    rating: 3,
  },
  {
    id: 10,
    img: "https://picsum.photos/seed/prod8/400/400",
    img2: "https://picsum.photos/seed/prod8b/400/400",
    name: "Sandals",
    description: "Comfortable everyday flat sandals",
    price: 399,
    oldPrice: 799,
    rating: 3,
  },
  {
    id: 11,
    img: "https://picsum.photos/seed/prod8/400/400",
    img2: "https://picsum.photos/seed/prod8b/400/400",
    name: "Sandals",
    description: "Comfortable everyday flat sandals",
    price: 399,
    oldPrice: 799,
    rating: 3,
  },
  {
    id: 12,
    img: "https://picsum.photos/seed/prod8/400/400",
    img2: "https://picsum.photos/seed/prod8b/400/400",
    name: "Sandals",
    description: "Comfortable everyday flat sandals",
    price: 399,
    oldPrice: 799,
    rating: 3,
  },
  {
    id: 13,
    img: "https://picsum.photos/seed/prod8/400/400",
    img2: "https://picsum.photos/seed/prod8b/400/400",
    name: "Sandals",
    description: "Comfortable everyday flat sandals",
    price: 399,
    oldPrice: 799,
    rating: 3,
  },
];